.TH "JANGLE" "1" "May 6, 2023"
.SH "NAME"
jangle \- a java snmp client
.SH "SYNOPSIS"
jangle subcommand [arguments]
.SH DESCRIPTION
The jangle utility allows browsing and retrieval of data from snmp
enabled devices.
.LP
To see the available subcommands, invoke jangle without any arguments.
.SH SEE ALSO
snmpwalk(1)
