#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Usage:
#
# ./build -doc
#    Generates the javadoc
#
# ./build
#    Builds all the java classes
#

PATH=/usr/jdk/instances/jdk1.8.0/bin:$PATH
export PATH

JKDIR=${0%/*}
LIBDIR=${JKDIR}/lib
JARLIBDIR=${LIBDIR}/java

JFJAR=${JARLIBDIR}/jfreechart-1.5.5.jar
JANGLEJAR=${JARLIBDIR}/jangle.jar
JINGLEJAR=${JARLIBDIR}/jingle.jar
JUMBLEJAR=${JARLIBDIR}/jumble.jar
SNMPJAR=${JARLIBDIR}/snmp.jar
MIBBLEJARS=${JARLIBDIR}/grammatica-1.4.jar:${JARLIBDIR}/mibble-2.3.jar
BUILDJARS=${JFJAR}:${JINGLEJAR}:${JUMBLEJAR}:${SNMPJAR}:${MIBBLEJARS}

#
# run
# ./build pmd
# to use this, you must have pmd in your path
#
# new PMD version has categories only
#
PMDCATRULES="security"
PMDCACHE="${HOME}/.pmd/cache.jangle"

case $1 in
doc|-doc)
	rm -fr javadoc
	mkdir javadoc
	javadoc -classpath "$BUILDJARS:." -d javadoc uk.co.petertribble.jangle
	exit 0
	;;
clean)
	rm -f $(find uk/co -type f -name '*.class')
	rm -f $(find . -type f -name '*~')
	rm -fr javadoc
	exit 0
	;;
pmd|-pmd)
	RULESETS=""
	shift
	for RULE in $PMDCATRULES "$@"
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	RULESETS=${RULESETS/,/}
	if [ ! -d "${HOME}/.pmd" ]; then
	    mkdir -p "${HOME}/.pmd"
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R "$RULESETS" --use-version java-1.8 --aux-classpath $(echo lib/java/* | sed 's= =:=g') 2>/dev/null
	pmd check --cache "${PMDCACHE}.html" -d help/*.html  -R category/html/bestpractices.xml 2>/dev/null
	exit 0
	;;
packages)
	sed s:INSTALLED=false:INSTALLED=true: jangle > jangle.installed
	./mkproto i386 $2 > prototype
	pkgmk -d /tmp -f prototype -r $(pwd) TRIBjangle
	pkgtrans -s /tmp /tmp/TRIBjangle.pkg TRIBjangle
	rm -fr /tmp/TRIBjangle
	ls -lh /tmp/TRIBjangle.pkg
	rm prototype
	rm jangle.installed
	rm -f depend
	exit 0
	;;
esac

XFLAGS="-Xlint -Xlint:-rawtypes"

javac ${XFLAGS} -classpath ".:${BUILDJARS}" uk/co/petertribble/jangle/*.java

jar -cmf jangle.manifest "${JANGLEJAR}" pixmaps/*.png help/*.html help/CDDL.txt properties/*.properties $(find uk/co -name '*.class')
